wandb_version: 1

model:
  desc: null
  value:
    n_width: 10
    n_coupling: 16
    input_width: 1
train:
  desc: null
  value:
    lr: 0.001
    batch_size: 1000
    epochs: 10
    device: mps
_wandb:
  desc: null
  value:
    python_version: 3.9.18
    cli_version: 0.16.2
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: true
    start_time: 1706873126.88936
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 2
      - 13
      - 16
      - 23
      4: 3.9.18
      5: 0.16.2
      8:
      - 1
      - 2
      - 4
      - 5
      13: darwin-arm64
